pipeline {
    agent any
    tools {
        maven '3.5.3'
        docker 'latest'
    }
    stages {
        stage('Example Build') {
            steps {
                echo 'Hello, Build'
            }
        }
        stage('Example Test') {
            steps {
                echo 'Hello, Test'
            }
        }
    }
}
